const Days = [
    "Monday",
    "Tuesday",
    "Wednesday",
    "Thursday",
    "Friday",
    "Saturday",
    "Sunday"
]

const Types = [
    "Arms",
    "Back",
    "Back + Arms",
    "Chest",
    "Chest + Shoulders",
    "Chest + Shoulders + Arms",
    "Legs",
    "Shoudlers"
]

const Exercises = [
    "1-arm Cable Row",
    "Ab wheel",
    "Airdyne Bike",
    "Angled or Upright Leg Press",
    "Barbell Romanian Deadlifts",
    "Bicycle Crunch",
    "Bodyweight Inverted Rows",
    "Bodyweight Lunges",
    "Bodyweight Weight Inverted Row",
    "Bosu crunches",
    "Bulgarian Split Squat",
    "Cable Alternating Front Raise",
    "Cable rear delt fly",
    "Cable Tricep Pushdowns with Dual Ropes",
    "Calf Raises - Seated",
    "Calf Raises - Standing",
    "Chest supported DB row",
    "DB Goblet Squat w/heels elevated",
    "DB Hammer Curls",
    "DB Lying Side Raise",
    "DB Romanian Deadlifts",
    "Decline DB Chest Press",
    "Decline DB Press",
    "Decline DB Tricep Extensions",
    "Dips",
    "DM Hammer Curls",
    "Extreme Decline Cable Dip",
    "EZ Bar Bicep Curls",
    "Flat DB Chest press with neutral Grip",
    "Flat DB Chest press",
    "Flutter kicks",
    "Forward and reverse lunges",
    "Forward walking Lunges with DBs",
    "Hanging leg raises",
    "Incline DB Row",
    "Incline Neutral Grip DB press",
    "Incline Sit-ups",
    "Landmine rotations",
    "Leaning Cable Lateral Raise",
    "Leg extensions",
    "Low Decline DB Press",
    "Lying leg raises",
    "Machine Crunches",
    "Moderate grip pushups",
    "Moderate Grip Pusups",
    "Neutral Grip Pulldowns",
    "Neutral Grip Pullups",
    "Oblique Cable twists",
    "Pallof Presses",
    "Pulldown crunches",
    "Reverse crunches",
    "Rope Facepull",
    "Seated DB Lateral Raise",
    "Seated leg curls",
    "Seated Low Row",
    "Seated Neutral Grip DB Shoulder Press",
    "Seated Wide Grip Row",
    "Side crunches",
    "Sled Pushes",
    "Stability ball crunches",
    "Stability ball or suspension trainer Pikes",
    "Standing Decline Cable Fly",
    "Standing Supinated DB Curls",
    "Standing Tricep Pushdown with Dual Ropes",
    "Supinated alternating DB curls",
    "Supinated Cable Curls",
    "Tricep Pushup",
    "Tricep Rope Pushdowns",
    "Wide Grip Seated Row",
]

export { Days, Types, Exercises }